
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_SPECIAL_SUCCESS: 'Cập nhật special thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_GROUP_ACP_SUCCESS: 'Cập nhật Group ACP thành công',
    CHANGE_GROUP_SUCCESS: 'Cập nhật Group thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    CHANGE_ORDERING_ERROR: 'Bị lỗi trong khi cập nhật ordering',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Thêm mới phần tử thành công',
    ADD_ERROR: 'Thêm mới phần tử thất bại, vui lòng kiểm tra quyền của bạn',
    EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công',
    EDIT_ERROR: 'Cập nhật thông tin phần tử thất bại, vui lòng kiểm tra quyền của bạn',
    ERROR_NAME: 'Chiều dài từ %d đến %d ký tự',
    ERROR_STRING: 'Chiều dài từ %d đến %d ký tự',
    ERROR_NUMBER: 'Phải là con số trong khoảntừ %d đến %d ',
    ERROR_NUMBER_INT: 'Phải là con số nguyên trong khoảntừ %d đến %d ',
    ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS: 'Phải là một giá trị khác rỗng',
    ERROR_SPECIAL: 'Phải là một giá trị khác rỗng',
    ERROR_GROUP: 'Phải là một giá trị khác rỗng',
    ERROR_GROUPACP: 'Phải là một giá trị khác rỗng',
    ERROR_FILE_REQUIRE: 'Vui lòng chọn file upload',
    ERROR_FILE_LIMIT: 'Kích thước file không phù hợp',
    ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ',
    ERROR_LOGIN: 'Username or password is incorrect',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Password is incorrect',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác',
    ERROR_DELETE: 'Xóa thất bại, Nếu có chi tiết, vui lòng xóa chi tiết trước!',
    ERROR_MSG_CHAT_TOO_SHORT: 'Chiều dài tin nhắn quá ngắn',
    
};